###########################################
# To use tasks : cargo install cargo-make #
###########################################

[tasks.default]
alias = "build_debug"

[tasks.build_debug]
command = "cargo"
args = ["build"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.doc]
command = "cargo"
args = ["doc", "--no-deps"]

[tasks.debug]
description = "Runs the main project with debug logger"
env = {"RUST_BACKTRACE"="full","RUST_LOG"="debug"}
command = "cargo"
args = ["run", "echo", ":::", "hello", "world"]

[tasks.run]
description = "Runs the main project without debug logger"
env = {"RUST_BACKTRACE"="full"}
command = "cargo"
args = ["run", "echo", ":::", "hello", "world"]

[tasks.test]
env = {"RUST_BACKTRACE"="full","RUST_LOG"="debug"}
command = "cargo"
args = ["test", "--", "--show-output"]

[tasks.test_th]
env = {"RUST_BACKTRACE"="full","RUST_LOG"="debug"}
command = "cargo"
args = ["test", "jobmanager_thread", "--", "--show-output"]

[tasks.test_cmd]
env = {"RUST_BACKTRACE"="full","RUST_LOG"="debug"}
command = "cargo"
args = ["test", "job_cmd", "--", "--show-output"]

[tasks.test_np]
env = {"RUST_BACKTRACE"="full","RUST_LOG"="debug"}
command = "cargo"
args = ["test", "test_notpanick", "--", "--show-output"]